name: bayesian-environment
channels: !!python/tuple
- defaults
dependencies:
- anaconda::backports_abc=0.4=py34_0
- anaconda::bokeh=0.12.1=py34_0
- anaconda::colorama=0.3.7=py34_0
- anaconda::cycler=0.10.0=py34_0
- anaconda::decorator=4.0.10=py34_0
- anaconda::ipykernel=4.5.0=py34_0
- anaconda::ipython_genutils=0.1.0=py34_0
- anaconda::jinja2=2.8=py34_1
- anaconda::jpeg=9b=vc10_0
- anaconda::jsonschema=2.5.1=py34_0
- anaconda::jupyter=1.0.0=py34_3
- anaconda::jupyter_client=4.4.0=py34_0
- anaconda::jupyter_console=5.0.0=py34_0
- anaconda::markupsafe=0.23=py34_1
- anaconda::mistune=0.7.3=py34_0
- anaconda::mkl=2017.0.1=0
- anaconda::nbconvert=4.2.0=py34_0
- anaconda::nbformat=4.1.0=py34_0
- anaconda::notebook=4.2.2=py34_0
- anaconda::numpy=1.11.3=py34_0
- anaconda::path.py=8.2.1=py34_0
- anaconda::patsy=0.4.1=py34_0
- anaconda::pickleshare=0.7.4=py34_0
- anaconda::pip=9.0.1=py34_1
- anaconda::python=3.4.5=0
- anaconda::python-dateutil=2.5.3=py34_0
- anaconda::pytz=2016.6.1=py34_0
- anaconda::pyyaml=3.11=py34_0
- anaconda::pyzmq=15.4.0=py34_0
- anaconda::requests=2.11.1=py34_0
- anaconda::scikit-learn=0.18.1=np111py34_1
- anaconda::scipy=0.18.1=np111py34_1
- anaconda::seaborn=0.7.1=py34_0
- anaconda::setuptools=27.2.0=py34_1
- anaconda::simplegeneric=0.8.1=py34_0
- anaconda::traitlets=4.2.2=py34_0
- anaconda::unidecode=0.04.19=py34_0
- anaconda::vc=10=0
- anaconda::vs2010_runtime=10.00.40219.1=2
- anaconda::wcwidth=0.1.7=py34_0
- anaconda::wheel=0.24.0=py34_0
- anaconda::win_unicode_console=0.5=py34_0
- anaconda::zlib=1.2.8=vc10_3
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::configparser=3.5.0=py34_0
- conda-forge::entrypoints=0.2.2=py34_1
- conda-forge::freetype=2.6.3=vc10_1
- conda-forge::ipython=5.1.0=py34_2
- conda-forge::ipywidgets=5.2.2=py34_2
- conda-forge::joblib=0.10.3=py34_0
- conda-forge::jupyter_core=4.1.1=py34_1
- conda-forge::libiconv=1.14=vc10_4
- conda-forge::libpng=1.6.28=vc10_0
- conda-forge::libpq=9.5.4=vc10_3
- conda-forge::libtiff=4.0.6=vc10_7
- conda-forge::libxml2=2.9.3=vc10_9
- conda-forge::matplotlib=2.0.0=np111py34_1
- conda-forge::oauthlib=1.1.2=py34_0
- conda-forge::openssl=1.0.2h=vc10_3
- conda-forge::pandas=0.18.1=np111py34_1
- conda-forge::pexpect=4.2.1=py34_0
- conda-forge::prompt_toolkit=1.0.7=py34_0
- conda-forge::psycopg2=2.6.2=py34_1
- conda-forge::pygments=2.1.3=py34_1
- conda-forge::pymc3=3.0=py34_0
- conda-forge::pyparsing=2.1.8=py34_0
- conda-forge::pyqt=4.11.4=py34_2
- conda-forge::qt=4.8.7=vc10_6
- conda-forge::qtconsole=4.2.1=py34_1
- conda-forge::sip=4.18=py34_1
- conda-forge::six=1.10.0=py34_1
- conda-forge::statsmodels=0.8.0=np111py34_0
- conda-forge::theano=0.8.2=py34_0
- conda-forge::tornado=4.4.1=py34_1
- conda-forge::tqdm=4.11.1=py34_0
- conda-forge::widgetsnbextension=1.2.6=py34_3
- conda-forge::yaml=0.1.6=vc10_0
- pip:
  - backports-abc==0.4
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - prettyprint==0.1.5
  - prompt-toolkit==1.0.7
  - requests-oauthlib==0.8.0
  - tweepy==3.5.0
  - win-unicode-console==0.5
