name: twitter-example
channels:
- intel
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- backports_abc=0.4=py34_0
- ca-certificates=2017.1.23=1
- colorama=0.3.7=py34_0
- configparser=3.5.0=py34_0
- cycler=0.10.0=py34_0
- decorator=4.0.10=py34_0
- entrypoints=0.2.2=py34_1
- freetype=2.6.3=vc10_1
- ipykernel=4.5.0=py34_0
- ipython=5.1.0=py34_2
- ipython_genutils=0.1.0=py34_0
- ipywidgets=5.2.2=py34_2
- jinja2=2.8=py34_1
- jpeg=9b=vc10_0
- jsonschema=2.5.1=py34_0
- jupyter_client=4.4.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_core=4.1.1=py34_1
- libiconv=1.14=vc10_4
- libpng=1.6.28=vc10_0
- libpq=9.5.4=vc10_3
- libtiff=4.0.6=vc10_7
- libxml2=2.9.3=vc10_9
- markupsafe=0.23=py34_1
- matplotlib=2.0.0=np111py34_1
- mistune=0.7.3=py34_0
- nbconvert=4.2.0=py34_0
- nbformat=4.1.0=py34_0
- notebook=4.2.2=py34_0
- oauthlib=1.1.2=py34_0
- openssl=1.0.2h=vc10_3
- pandas=0.18.1=np111py34_1
- path.py=8.2.1=py34_0
- patsy=0.4.1=py34_0
- pexpect=4.2.1=py34_0
- prompt_toolkit=1.0.7=py34_0
- psycopg2=2.6.2=py34_1
- pygments=2.1.3=py34_1
- pyparsing=2.1.8=py34_0
- pyqt=4.11.4=py34_2
- python-dateutil=2.5.3=py34_0
- pytz=2016.6.1=py34_0
- pyyaml=3.11=py34_0
- pyzmq=15.4.0=py34_0
- qt=4.8.7=vc10_6
- qtconsole=4.2.1=py34_1
- requests=2.11.1=py34_0
- seaborn=0.7.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.18=py34_1
- six=1.10.0=py34_1
- statsmodels=0.8.0=np111py34_0
- tornado=4.4.1=py34_1
- traitlets=4.2.2=py34_0
- unidecode=0.04.19=py34_0
- vc=10=0
- wcwidth=0.1.7=py34_0
- widgetsnbextension=1.2.6=py34_3
- win_unicode_console=0.5=py34_0
- yaml=0.1.6=vc10_0
- zlib=1.2.8=vc10_3
- bokeh=0.12.1=py34_0
- jupyter=1.0.0=py34_3
- mkl=11.3.3=1
- numpy=1.11.1=py34_1
- pickleshare=0.7.4=py34_0
- pip=9.0.1=py34_1
- python=3.4.5=0
- scipy=0.18.0=np111py34_0
- setuptools=27.2.0=py34_1
- vs2010_runtime=10.00.40219.1=2
- wheel=0.24.0=py34_0
- pip:
  - backports-abc==0.4
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - prettyprint==0.1.5
  - prompt-toolkit==1.0.7
  - requests-oauthlib==0.8.0
  - tweepy==3.5.0
  - win-unicode-console==0.5
